/* GENERATED by tools/build-plan.js from /Users/Reid Hu/OrbitOS/20_Project/GRE_Physics_Prep/01_Syllabus_&_Plan/8-Week-Syllabus.md
   do not hand-edit; regenerate after syllabus changes
   source updated: 2026-09-11 */
window.PGRE = window.PGRE || {};

PGRE.PLAN_META = {
  "source": "/Users/Reid Hu/OrbitOS/20_Project/GRE_Physics_Prep/01_Syllabus_&_Plan/8-Week-Syllabus.md",
  "version": "2026-09-11",
  "examDate": "2026-11-01"
};

PGRE.PLAN_SETS = {
  "01": "Kinematics & Newton's Laws",
  "02": "Work, Energy & Momentum Conservation",
  "03": "Oscillations & Harmonic Motion",
  "04": "Central Forces & Orbital Mechanics",
  "05": "Rotational Dynamics & Rigid Bodies",
  "06": "Lagrangian & Hamiltonian Formalism",
  "07": "Non-Inertial Frames & Fluid Dynamics",
  "08": "Electrostatics & Field Potentials",
  "09": "Capacitors, Dielectrics & DC Circuits",
  "10": "Magnetostatics & Ampère's Law",
  "11": "Induction, Inductance & RL/LC Circuits",
  "12": "Maxwell's Equations & Electromagnetic Waves",
  "13": "Fields in Matter, Boundary Conditions & AC Circuits",
  "14": "Wave Properties, Standing Waves & Sound",
  "15": "Geometric Optics & Polarization",
  "16": "Interference & Diffraction",
  "17": "Laws of Thermodynamics & State Equations",
  "18": "Heat Engines, Cycles & Entropy",
  "19": "Kinetic Theory & Equipartition",
  "20": "Statistical Ensembles & Quantum Statistics",
  "21": "1D Wells, Barriers & Bound States",
  "22": "Harmonic Oscillator & Operator Algebra",
  "23": "Formalism, Superposition & Measurement",
  "24": "Hydrogen Atom & 3D Potentials",
  "25": "Spin, Perturbation Theory & Identical Particles",
  "26": "Atomic Structure & Early Quantum",
  "27": "Spin-Orbit, Fine Structure & Zeeman Effect",
  "28": "Relativistic Kinematics & Space-Time",
  "29": "Relativistic Dynamics & 4-Vectors",
  "30": "Nuclear Properties, Decays & Reactions",
  "31": "Lab Equipment, Circuits & Instrumentation",
  "32": "Error Analysis & Data Reduction",
  "33": "Particle Physics & Conservation Laws",
  "34": "Condensed Matter & Solid State Physics",
  "35": "Astrophysics, Cosmology & Comprehensive Review"
};

PGRE.PLAN = [
  {
    "id": "p0",
    "name": "Week 0 · Historical",
    "desc": "Sep 7–13 — pre-rewrite week. Kept so the Set 02 carry rule resolves; not replayed.",
    "weeks": [
      {
        "id": "w0",
        "start": "2026-09-07",
        "end": "2026-09-13",
        "title": "Classical Mechanics (historical)",
        "focus": "CM",
        "topics": [
          "cm"
        ],
        "hours": 9,
        "notes": "Assigned: CM Sets 01–05. Set 01 done 2026-09-08. Set 02 open as of 2026-09-11. Do not restart Week 0 on or after Sep 14.",
        "timedSets": [
          1,
          2,
          3,
          4,
          5
        ],
        "historical": true
      }
    ]
  },
  {
    "id": "p1",
    "name": "Live calendar · Sep 14 – Oct 25",
    "desc": "5+6+2 weekly load (~16 h): timed sets, formula recall, misses-first extras. Checkpoints Oct 4 and Oct 25.",
    "weeks": [
      {
        "id": "w1",
        "start": "2026-09-14",
        "end": "2026-09-20",
        "title": "Classical Mechanics",
        "focus": "CM 20%",
        "topics": [
          "cm"
        ],
        "hours": 16,
        "notes": "Kahn Ch. 1, Prep Studio CM Bank",
        "timedSets": [
          3,
          4,
          5,
          6,
          7
        ],
        "carry": {
          "set": 2,
          "deadline": "2026-09-14",
          "timed": [
            2,
            3,
            4,
            5,
            6
          ],
          "extras": [
            7
          ]
        },
        "carryExtras": [
          7
        ]
      },
      {
        "id": "w2",
        "start": "2026-09-21",
        "end": "2026-09-27",
        "title": "Electromagnetism + Optics",
        "focus": "EM 18% + Optics 8%",
        "topics": [
          "em",
          "ow"
        ],
        "hours": 16,
        "notes": "Kahn Ch. 2 + Ch. 3",
        "timedSets": [
          8,
          9,
          10,
          14,
          15
        ],
        "carryExtras": [
          7
        ]
      },
      {
        "id": "w3",
        "start": "2026-09-28",
        "end": "2026-10-04",
        "title": "EM + Optics — diagnostic week",
        "focus": "EM + Optics",
        "topics": [
          "em",
          "ow"
        ],
        "hours": 16,
        "notes": "Sun Oct 4: paper diagnostic GR0177/GR0877 replaces the 5th timed",
        "timedSets": [
          11,
          12,
          13,
          16
        ],
        "checkpoint": {
          "id": "w3-checkpoint",
          "label": "Sun Oct 4 — paper diagnostic GR0177/GR0877 (replaces the 5th timed)"
        }
      },
      {
        "id": "w4",
        "start": "2026-10-05",
        "end": "2026-10-11",
        "title": "Thermodynamics",
        "focus": "Thermo 10%",
        "topics": [
          "th"
        ],
        "hours": 16,
        "notes": "Kahn Ch. 4. Optics not parked (done in W2–W3)",
        "timedSets": [
          17,
          18,
          19,
          20
        ],
        "reviewSlot": true
      },
      {
        "id": "w5",
        "start": "2026-10-12",
        "end": "2026-10-18",
        "title": "Quantum Mechanics",
        "focus": "QM 13%",
        "topics": [
          "qm"
        ],
        "hours": 16,
        "notes": "Kahn Ch. 5.1–5.6",
        "timedSets": [
          21,
          22,
          23,
          24,
          25
        ]
      },
      {
        "id": "w6",
        "start": "2026-10-19",
        "end": "2026-10-25",
        "title": "Atomic + Relativity — rehearsal week",
        "focus": "Atomic 10% + SR 6%",
        "topics": [
          "at",
          "sr"
        ],
        "hours": 16,
        "notes": "Kahn Ch. 5.7 & Ch. 6. Sun Oct 25: 70Q/120 computer rehearsal (2024 Practice Book) replaces the 5th timed. Extra light that day. Set 30 (nuclear properties) → extras after misses.",
        "timedSets": [
          26,
          27,
          28,
          29
        ],
        "checkpoint": {
          "id": "w6-checkpoint",
          "label": "Sun Oct 25 — 70Q/120 computer rehearsal, 2024 Practice Book (replaces the 5th timed)"
        }
      }
    ]
  },
  {
    "id": "p2",
    "name": "Exam week · Oct 26 – Nov 1",
    "desc": "Taper: Sets 32–33 new only, replays, logistics, rest. Exam Sun Nov 1, 14:00.",
    "weeks": [
      {
        "id": "w7",
        "start": "2026-10-26",
        "end": "2026-11-01",
        "title": "Lab + Specialized — taper & exam",
        "focus": "Lab 6% + Specialized 9%",
        "topics": [
          "lb",
          "sp"
        ],
        "hours": 8,
        "notes": "Fri logistics/formula; Sat sleep/travel; Sun exam. Deferred new: 30, 31, 34, 35 → extras after misses, else after 2026-11-01",
        "timedSets": [
          32,
          33
        ],
        "deferred": [
          30,
          31,
          34,
          35
        ],
        "replay": true,
        "examDay": true
      }
    ]
  }
];
